'use client'

// ── CSV export ────────────────────────────────────────────────────────────────
function downloadCSV(filename: string, rows: string[][]) {
  const csv = rows.map(r => r.map(c => `"${String(c ?? '').replace(/"/g, '""')}"`).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

// ── PDF export (via print dialog) ────────────────────────────────────────────
function downloadPDF(filename: string, htmlContent: string) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`<!DOCTYPE html><html><head>
    <title>${filename}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 12px; color: #111; padding: 24px; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 20px; color: #1e3a8a; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-bottom: 16px; }
      h2 { font-size: 15px; color: #1e3a8a; margin: 16px 0 6px; }
      table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 11px; }
      th { background: #1e3a8a; color: white; padding: 6px 8px; text-align: left; }
      td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
      tr:nth-child(even) td { background: #f8fafc; }
      .badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 10px; font-weight: bold; }
      .high { background: #fee2e2; color: #dc2626; }
      .medium { background: #fef3c7; color: #d97706; }
      .low { background: #f0fdf4; color: #16a34a; }
      .likely { background: #f0fdf4; color: #16a34a; }
      .possible { background: #fef3c7; color: #d97706; }
      .unlikely { background: #fee2e2; color: #dc2626; }
      p { margin: 4px 0 8px; line-height: 1.5; }
      .meta { color: #6b7280; font-size: 10px; margin-bottom: 16px; }
      @media print { body { padding: 0; } }
    </style>
  </head><body>${htmlContent}<script>window.onload=()=>{window.print();}</script></body></html>`)
  win.document.close()
}

// ── DOCX export (using docx npm package loaded via CDN) ───────────────────────
async function downloadDOCX(filename: string, buildFn: () => Promise<Uint8Array>) {
  const bytes = await buildFn()
  const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename + '.docx'; a.click()
  URL.revokeObjectURL(url)
}

// ─────────────────────────────────────────────────────────────────────────────
// BACKLINKS EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type BacklinkOp = {
  site_name: string; site_url: string; domain_authority: string
  link_type: string; angle: string; why_relevant: string
  contact_approach: string; difficulty: string; impact: string
}

export function exportBacklinksCSV(data: { summary?: string; opportunities?: BacklinkOp[] }) {
  const rows = [
    ['Site Name', 'Site URL', 'Domain Authority', 'Link Type', 'Pitch Angle', 'Why Relevant', 'Contact Approach', 'Difficulty', 'Impact'],
    ...(data.opportunities ?? []).map(op => [
      op.site_name, op.site_url, op.domain_authority,
      op.link_type?.replace(/_/g, ' '), op.angle, op.why_relevant,
      op.contact_approach, op.difficulty, op.impact,
    ]),
  ]
  downloadCSV('semantictoolz-backlinks.csv', rows)
}

export function exportBacklinksPDF(data: { summary?: string; opportunities?: BacklinkOp[] }) {
  const rows = (data.opportunities ?? []).map(op => `
    <tr>
      <td><strong>${op.site_name}</strong><br/><small>${op.site_url}</small></td>
      <td>${op.link_type?.replace(/_/g, ' ')}</td>
      <td><span class="badge ${op.domain_authority}">${op.domain_authority}</span></td>
      <td>${op.angle}</td>
      <td>${op.contact_approach}</td>
      <td><span class="badge ${op.difficulty}">${op.difficulty}</span></td>
      <td><span class="badge ${op.impact}">${op.impact}</span></td>
    </tr>`).join('')
  const html = `
    <h1>Relevant Backlinks Report</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    <table>
      <thead><tr><th>Site</th><th>Type</th><th>DA</th><th>Pitch Angle</th><th>How to Contact</th><th>Difficulty</th><th>Impact</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`
  downloadPDF('SemanticToolz Backlinks Report', html)
}

export async function exportBacklinksDOCX(data: { summary?: string; opportunities?: BacklinkOp[] }) {
  await downloadDOCX('semantictoolz-backlinks', async () => {
    const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
            HeadingLevel, AlignmentType, WidthType, BorderStyle, ShadingType } = await import('docx')
    const border = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }
    const borders = { top: border, bottom: border, left: border, right: border }
    const cell = (text: string, bold = false, bg?: string) => new TableCell({
      borders,
      width: { size: 1300, type: WidthType.DXA },
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      shading: bg ? { fill: bg, type: ShadingType.CLEAR } : undefined,
      children: [new Paragraph({ children: [new TextRun({ text, bold, size: 18 })] })],
    })
    const headerRow = new TableRow({
      children: ['Site Name', 'URL', 'Type', 'DA', 'Pitch Angle', 'Contact', 'Difficulty', 'Impact']
        .map(h => cell(h, true, '1E3A8A').constructor === TableCell
          ? new TableCell({ borders, width: { size: 1300, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
              shading: { fill: '1E3A8A', type: ShadingType.CLEAR },
              children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18, color: 'FFFFFF' })] })] })
          : cell(h, true, '1E3A8A')),
    })
    // rebuild header properly
    const hdr = new TableRow({
      children: ['Site Name', 'URL', 'Type', 'DA', 'Pitch Angle', 'Contact', 'Difficulty', 'Impact'].map(h =>
        new TableCell({ borders, width: { size: 1170, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
          shading: { fill: '1E3A8A', type: ShadingType.CLEAR },
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18, color: 'FFFFFF' })] })] })
      ),
    })
    const dataRows = (data.opportunities ?? []).map(op => new TableRow({
      children: [op.site_name, op.site_url, op.link_type?.replace(/_/g,' '), op.domain_authority,
                 op.angle, op.contact_approach, op.difficulty, op.impact]
        .map(t => new TableCell({ borders, width: { size: 1170, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
          children: [new Paragraph({ children: [new TextRun({ text: t ?? '', size: 18 })] })] })),
    }))
    const doc = new Document({
      sections: [{
        properties: { page: { size: { width: 15840, height: 12240 }, margin: { top: 1440, right: 1080, bottom: 1440, left: 1080 } } },
        children: [
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun('Relevant Backlinks Report')] }),
          new Paragraph({ children: [new TextRun({ text: `Generated by SemanticToolz · ${new Date().toLocaleDateString()}`, size: 18, color: '6B7280' })] }),
          ...(data.summary ? [new Paragraph({ children: [new TextRun({ text: data.summary, size: 20 })] })] : []),
          new Paragraph({ children: [] }),
          new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: Array(8).fill(1170), rows: [hdr, ...dataRows] }),
        ],
      }],
    })
    return Packer.toBuffer(doc)
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// CITE TRACKER EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type TrackerResult = {
  query: string; citation_likelihood: number; citation_verdict: string
  simulated_ai_response: string; reasons_for_citation: string[]
  reasons_against_citation: string[]; what_would_increase_citation: string
}

export function exportTrackerCSV(data: { overall_citation_score?: number; verdict?: string; results?: TrackerResult[] }) {
  const rows = [
    ['Query', 'Citation Score', 'Verdict', 'Simulated AI Response', 'Reasons For', 'Reasons Against', 'What Would Help'],
    ...(data.results ?? []).map(r => [
      r.query, String(r.citation_likelihood), r.citation_verdict,
      r.simulated_ai_response,
      (r.reasons_for_citation ?? []).join('; '),
      (r.reasons_against_citation ?? []).join('; '),
      r.what_would_increase_citation,
    ]),
  ]
  downloadCSV('semantictoolz-cite-tracker.csv', rows)
}

export function exportTrackerPDF(data: { overall_citation_score?: number; verdict?: string; results?: TrackerResult[] }) {
  const rows = (data.results ?? []).map(r => `
    <tr>
      <td>${r.query}</td>
      <td style="text-align:center"><strong>${r.citation_likelihood}</strong></td>
      <td><span class="badge ${r.citation_verdict}">${r.citation_verdict}</span></td>
      <td style="font-size:10px">${r.simulated_ai_response}</td>
      <td style="font-size:10px">${(r.reasons_for_citation ?? []).join('<br>')}</td>
      <td style="font-size:10px">${r.what_would_increase_citation}</td>
    </tr>`).join('')
  const html = `
    <h1>AI Citation Tracker Report</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <h2>Overall Citation Score: ${data.overall_citation_score ?? 0}/100</h2>
    <p>${data.verdict ?? ''}</p>
    <table>
      <thead><tr><th>Query</th><th>Score</th><th>Verdict</th><th>AI Response</th><th>Why Cited</th><th>How to Improve</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`
  downloadPDF('SemanticToolz Cite Tracker Report', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// LOCAL SEO EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export function exportLocalCSV(data: Record<string, unknown>, subTool: string) {
  let rows: string[][] = []
  if (subTool === 'entities') {
    const d = data as { priority_additions?: Array<{ entity: string; type: string; why: string; example_sentence: string }> }
    rows = [
      ['Entity', 'Type', 'Why Important', 'Example Sentence'],
      ...(d.priority_additions ?? []).map(e => [e.entity, e.type, e.why, e.example_sentence]),
    ]
  } else if (subTool === 'queries') {
    const d = data as { queries?: Array<{ query: string; platform: string; intent_type: string; coverage_score: number; verdict: string; gap: string; fix: string }> }
    rows = [
      ['Query', 'Platform', 'Intent', 'Coverage Score', 'Verdict', 'Gap', 'Fix'],
      ...(d.queries ?? []).map(q => [q.query, q.platform, q.intent_type, String(q.coverage_score), q.verdict, q.gap, q.fix]),
    ]
  } else if (subTool === 'gbp') {
    const d = data as { gbp_posts?: Array<{ type: string; title: string; body: string; cta: string }>; qa_pairs?: Array<{ question: string; answer: string }> }
    rows = [
      ['Type', 'Title / Question', 'Body / Answer', 'CTA'],
      ...(d.gbp_posts ?? []).map(p => ['Post - ' + p.type, p.title, p.body, p.cta]),
      ...(d.qa_pairs ?? []).map(q => ['Q&A', q.question, q.answer, '']),
    ]
  } else {
    rows = [['Key', 'Value'], ...Object.entries(data).map(([k, v]) => [k, JSON.stringify(v)])]
  }
  downloadCSV(`semantictoolz-local-${subTool}.csv`, rows)
}

export function exportLocalPDF(data: Record<string, unknown>, subTool: string, city: string) {
  const toolLabels: Record<string, string> = {
    entities: 'Local Entity Analysis', nap: 'NAP + Schema Audit',
    queries: 'Local AI Query Map', gbp: 'GBP Content',
  }
  let content = ''
  if (subTool === 'entities') {
    const d = data as { local_entity_score?: number; summary?: string; priority_additions?: Array<{ entity: string; type: string; why: string; example_sentence: string }> }
    content = `<h2>Entity Score: ${d.local_entity_score ?? 0}/100</h2><p>${d.summary ?? ''}</p>
    <table><thead><tr><th>Entity</th><th>Type</th><th>Why Important</th><th>Example</th></tr></thead><tbody>
    ${(d.priority_additions ?? []).map(e => `<tr><td>${e.entity}</td><td>${e.type}</td><td>${e.why}</td><td><em>${e.example_sentence}</em></td></tr>`).join('')}
    </tbody></table>`
  } else if (subTool === 'nap') {
    const d = data as { nap_audit?: { name_found: boolean; address_found: boolean; phone_found: boolean; nap_score: number; consistency_issues: string[] }; json_ld?: string }
    content = `<h2>NAP Audit Score: ${d.nap_audit?.nap_score ?? 0}/100</h2>
    <p>Name: ${d.nap_audit?.name_found ? '✓' : '✗'} | Address: ${d.nap_audit?.address_found ? '✓' : '✗'} | Phone: ${d.nap_audit?.phone_found ? '✓' : '✗'}</p>
    ${d.nap_audit?.consistency_issues?.length ? `<h2>Issues</h2><ul>${d.nap_audit.consistency_issues.map(i => `<li>${i}</li>`).join('')}</ul>` : ''}
    ${d.json_ld ? `<h2>Generated JSON-LD Schema</h2><pre style="font-size:9px;background:#f8f8f8;padding:8px;border-radius:4px;overflow-wrap:break-word">${d.json_ld}</pre>` : ''}`
  } else if (subTool === 'queries') {
    const d = data as { queries?: Array<{ query: string; platform: string; verdict: string; coverage_score: number; fix: string }> }
    content = `<table><thead><tr><th>Query</th><th>Platform</th><th>Score</th><th>Verdict</th><th>Fix</th></tr></thead><tbody>
    ${(d.queries ?? []).map(q => `<tr><td>${q.query}</td><td>${q.platform}</td><td>${q.coverage_score}</td><td><span class="badge ${q.verdict}">${q.verdict}</span></td><td>${q.fix}</td></tr>`).join('')}
    </tbody></table>`
  } else if (subTool === 'gbp') {
    const d = data as { gbp_posts?: Array<{ type: string; title: string; body: string; cta: string; hashtags?: string[] }>; qa_pairs?: Array<{ question: string; answer: string }>; gbp_description?: string }
    content = `${d.gbp_description ? `<h2>GBP Description</h2><p>${d.gbp_description}</p>` : ''}
    <h2>Posts</h2>${(d.gbp_posts ?? []).map(p => `<p><strong>${p.type.toUpperCase()} — ${p.title}</strong><br>${p.body}<br><em>CTA: ${p.cta}</em></p>`).join('')}
    <h2>Q&amp;A Pairs</h2>${(d.qa_pairs ?? []).map(q => `<p><strong>Q: ${q.question}</strong><br>A: ${q.answer}</p>`).join('')}`
  }
  downloadPDF(`SemanticToolz Local SEO - ${toolLabels[subTool]}`, `
    <h1>Local SEO — ${toolLabels[subTool] ?? subTool}</h1>
    <p class="meta">Location: ${city} · Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${content}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// SERP AUDIT EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type SerpData = {
  competitors?: Array<{ rank: number; url: string; authority: string; page_type: string; word_count: string; eeat: string }>
  root_causes?: Array<{ dimension: string; diagnosis: string; severity: string }>
  action_plan?: { phase1?: Array<{ task: string; why: string; effort: string; impact: string }>; phase2?: Array<{ task: string; why: string; effort: string; impact: string }>; phase3?: Array<{ task: string; why: string; effort: string; impact: string }> }
  rank_projection?: Array<{ month: string; position: number }>
  _meta?: { url: string; keyword: string; position?: string }
}

export function exportSerpCSV(data: SerpData) {
  const rows: string[][] = []
  rows.push(['SERP AUDIT REPORT'], ['Keyword', data._meta?.keyword ?? ''], ['Target URL', data._meta?.url ?? ''], [''])
  rows.push(['COMPETITORS'], ['Rank', 'URL', 'Authority', 'Page Type', 'Word Count', 'E-E-A-T'])
  ;(data.competitors ?? []).forEach(c => rows.push([String(c.rank), c.url, c.authority, c.page_type, c.word_count, c.eeat]))
  rows.push([''], ['ROOT CAUSES'], ['Dimension', 'Diagnosis', 'Severity'])
  ;(data.root_causes ?? []).forEach(rc => rows.push([rc.dimension, rc.diagnosis, rc.severity]))
  rows.push([''], ['ACTION PLAN — PHASE 1 (Weeks 1-4)'], ['Task', 'Why', 'Effort', 'Impact'])
  ;(data.action_plan?.phase1 ?? []).forEach(t => rows.push([t.task, t.why, t.effort, t.impact]))
  rows.push([''], ['ACTION PLAN — PHASE 2 (Weeks 5-10)'], ['Task', 'Why', 'Effort', 'Impact'])
  ;(data.action_plan?.phase2 ?? []).forEach(t => rows.push([t.task, t.why, t.effort, t.impact]))
  rows.push([''], ['RANK PROJECTION'], ['Month', 'Projected Position'])
  ;(data.rank_projection ?? []).forEach(r => rows.push([r.month, String(r.position)]))
  downloadCSV('semantictoolz-serp-audit.csv', rows)
}

export function exportSerpPDF(data: SerpData) {
  const compRows = (data.competitors ?? []).map(c => `
    <tr><td>${c.rank}</td><td style="font-size:10px">${c.url}</td><td>${c.authority}</td><td>${c.page_type}</td><td>${c.word_count}</td><td>${c.eeat}</td></tr>`).join('')
  const rcRows = (data.root_causes ?? []).map(rc => `
    <tr><td>${rc.dimension}</td><td>${rc.diagnosis}</td><td><span class="badge ${rc.severity}">${rc.severity}</span></td></tr>`).join('')
  const phaseTable = (items: Array<{ task: string; why: string; effort: string; impact: string }> = [], label: string) =>
    `<h2>${label}</h2><table><thead><tr><th>Task</th><th>Why</th><th>Effort</th><th>Impact</th></tr></thead><tbody>
    ${items.map(t => `<tr><td>${t.task}</td><td>${t.why}</td><td>${t.effort}</td><td><span class="badge ${t.impact}">${t.impact}</span></td></tr>`).join('')}</tbody></table>`
  const html = `
    <h1>SERP Competitor Audit</h1>
    <p class="meta">Keyword: <strong>${data._meta?.keyword ?? ''}</strong> · Target: ${data._meta?.url ?? ''} · Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <h2>Top Competitors</h2>
    <table><thead><tr><th>#</th><th>URL</th><th>Authority</th><th>Page Type</th><th>Word Count</th><th>E-E-A-T</th></tr></thead><tbody>${compRows}</tbody></table>
    <h2>Root Causes</h2>
    <table><thead><tr><th>Dimension</th><th>Diagnosis</th><th>Severity</th></tr></thead><tbody>${rcRows}</tbody></table>
    ${phaseTable(data.action_plan?.phase1, 'Phase 1 — Weeks 1–4: Quick Wins')}
    ${phaseTable(data.action_plan?.phase2, 'Phase 2 — Weeks 5–10: Authority Building')}
    ${phaseTable(data.action_plan?.phase3, 'Phase 3 — Weeks 11–20: Content & Links')}
    ${data.rank_projection?.length ? `<h2>Rank Projection</h2><table><thead><tr><th>Month</th><th>Projected Position</th></tr></thead><tbody>
    ${data.rank_projection.map(r => `<tr><td>${r.month}</td><td>#${r.position}</td></tr>`).join('')}</tbody></table>` : ''}`
  downloadPDF('SemanticToolz SERP Audit', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// TOPICAL AUTHORITY EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type TopicalPillar = {
  title: string; slug: string; monthly_searches: string; covered: boolean; ai_cite_score: number
  clusters: Array<{ title: string; slug: string; difficulty: string; monthly_searches: string; covered: boolean; primary_keyword: string }>
}

type TopicalData = {
  topic?: string; authority_score?: number; coverage_grade?: string
  pillar_pages?: TopicalPillar[]
  coverage_stats?: { total_topics: number; covered: number; missing: number; coverage_pct: number }
  content_calendar?: Array<{ week: number; title: string; type: string; why_now: string }>
}

export function exportTopicalCSV(data: TopicalData) {
  const rows: string[][] = []
  rows.push(['TOPICAL AUTHORITY MAP'], ['Niche', data.topic ?? ''], ['Authority Score', String(data.authority_score ?? 0)], ['Coverage Grade', data.coverage_grade ?? ''], [''])
  rows.push(['PILLAR & CLUSTER MAP'], ['Type', 'Title', 'Monthly Searches', 'Covered', 'Difficulty', 'AI Cite Score', 'Primary Keyword'])
  ;(data.pillar_pages ?? []).forEach(p => {
    rows.push(['PILLAR', p.title, p.monthly_searches, p.covered ? 'Yes' : 'No', '', String(p.ai_cite_score), ''])
    ;(p.clusters ?? []).forEach(c => rows.push(['  Cluster', c.title, c.monthly_searches, c.covered ? 'Yes' : 'No', c.difficulty, '', c.primary_keyword]))
  })
  rows.push([''], ['CONTENT CALENDAR'], ['Week', 'Title', 'Type', 'Why Now'])
  ;(data.content_calendar ?? []).forEach(c => rows.push([`Week ${c.week}`, c.title, c.type, c.why_now]))
  downloadCSV('semantictoolz-topical-authority.csv', rows)
}

export function exportTopicalPDF(data: TopicalData) {
  const pillarRows = (data.pillar_pages ?? []).flatMap(p => [
    `<tr style="background:#EFF6FF"><td colspan="5"><strong>${p.title}</strong></td><td>${p.monthly_searches}</td><td>${p.covered ? '✓' : '✗'}</td><td>${p.ai_cite_score}</td></tr>`,
    ...(p.clusters ?? []).map(c => `<tr><td style="padding-left:20px">↳ ${c.title}</td><td colspan="4" style="font-size:10px;color:#6b7280">${c.primary_keyword}</td><td>${c.monthly_searches}</td><td>${c.covered ? '✓' : '✗'}</td><td>${c.difficulty}</td></tr>`),
  ]).join('')
  const calRows = (data.content_calendar ?? []).map(c => `<tr><td>Week ${c.week}</td><td>${c.title}</td><td>${c.type}</td><td>${c.why_now}</td></tr>`).join('')
  const html = `
    <h1>Topical Authority Map</h1>
    <p class="meta">Niche: <strong>${data.topic ?? ''}</strong> · Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 12px 4px 0"><strong>Authority Score</strong></td><td>${data.authority_score ?? 0}/100</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Coverage Grade</strong></td><td>${data.coverage_grade ?? ''}</td></tr>
      <tr><td style="padding:4px 12px 4px 0"><strong>Total Topics</strong></td><td>${data.coverage_stats?.total_topics ?? 0} (${data.coverage_stats?.covered ?? 0} covered, ${data.coverage_stats?.missing ?? 0} missing)</td></tr>
    </table>
    <h2>Pillar & Cluster Map</h2>
    <table><thead><tr><th>Topic</th><th colspan="4"></th><th>Searches/mo</th><th>Covered</th><th>Score/Difficulty</th></tr></thead><tbody>${pillarRows}</tbody></table>
    ${calRows ? `<h2>Content Calendar</h2><table><thead><tr><th>Week</th><th>Title</th><th>Type</th><th>Why Now</th></tr></thead><tbody>${calRows}</tbody></table>` : ''}`
  downloadPDF('SemanticToolz Topical Authority', html)
}

// ─────────────────────────────────────────────────────────────────────────────
// SCORES (main dashboard) EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type AnalysisResult = {
  overall_score: number; grade: string; summary: string
  scores: Record<string, number>
  top_issues: Array<{ issue: string; impact: string; category: string; fix: string }>
  quick_wins: string[]; entity_gaps: string[]; llm_citation_tip: string
}

const SCORE_DIMS = [
  { key: 'technical_seo',          label: 'Technical SEO',      weight: '10%' },
  { key: 'on_page_seo',            label: 'On-Page SEO',        weight: '20%' },
  { key: 'entity_optimization',    label: 'Entity Optimization', weight: '15%' },
  { key: 'eeat_signals',           label: 'E-E-A-T Signals',    weight: '15%' },
  { key: 'semantic_richness',      label: 'Semantic Richness',   weight: '10%' },
  { key: 'llm_citation_triggers',  label: 'LLM Citation',       weight: '20%' },
  { key: 'structured_data',        label: 'Structured Data',    weight: '5%'  },
  { key: 'authority_reinforcement',label: 'Authority',          weight: '5%'  },
]

export function exportScoresCSV(data: AnalysisResult) {
  const rows: string[][] = [
    ['CONTENT ANALYSIS REPORT'],
    ['Overall Score', String(data.overall_score), 'Grade', data.grade],
    ['Summary', data.summary],
    [''],
    ['SCORE BREAKDOWN'],
    ['Dimension', 'Score', 'Weight'],
    ...SCORE_DIMS.map(d => [d.label, String(data.scores?.[d.key] ?? 0), d.weight]),
    [''],
    ['TOP ISSUES'],
    ['Issue', 'Impact', 'Category', 'Fix'],
    ...(data.top_issues ?? []).map(i => [i.issue, i.impact, i.category, i.fix]),
    [''],
    ['QUICK WINS'],
    ...(data.quick_wins ?? []).map(w => [w]),
    [''],
    ['MISSING ENTITIES'],
    ...(data.entity_gaps ?? []).map(e => [e]),
  ]
  downloadCSV('semantictoolz-scores.csv', rows)
}

export function exportScoresPDF(data: AnalysisResult) {
  const dimRows = SCORE_DIMS.map(d => {
    const v = data.scores?.[d.key] ?? 0
    const bar = '█'.repeat(Math.round(v / 10)) + '░'.repeat(10 - Math.round(v / 10))
    return `<tr><td>${d.label}</td><td style="font-family:monospace;font-size:10px;letter-spacing:-1px">${bar}</td><td style="text-align:right"><strong>${v}</strong>/100</td><td style="color:#6b7280;font-size:10px">${d.weight}</td></tr>`
  }).join('')
  const issueRows = (data.top_issues ?? []).map(i => `<tr><td>${i.issue}</td><td><span class="badge ${i.impact}">${i.impact}</span></td><td style="font-size:10px;color:#6b7280">${i.category}</td><td style="font-size:10px">${i.fix}</td></tr>`).join('')
  downloadPDF('SemanticToolz Content Score', `
    <h1>Content Analysis Report</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall Score</strong></td><td><span style="font-size:24px;font-weight:900">${data.overall_score}</span>/100</td><td style="padding-left:24px"><strong>Grade</strong></td><td style="font-size:24px;font-weight:900">${data.grade}</td></tr>
    </table>
    <p>${data.summary}</p>
    <h2>Score Breakdown</h2>
    <table><thead><tr><th>Dimension</th><th>Visual</th><th>Score</th><th>Weight</th></tr></thead><tbody>${dimRows}</tbody></table>
    <h2>Top Issues</h2>
    <table><thead><tr><th>Issue</th><th>Impact</th><th>Category</th><th>Fix</th></tr></thead><tbody>${issueRows}</tbody></table>
    <h2>Quick Wins</h2>
    <ul>${(data.quick_wins ?? []).map(w => `<li style="margin-bottom:4px">${w}</li>`).join('')}</ul>
    ${data.entity_gaps?.length ? `<h2>Missing Entities</h2><p>${data.entity_gaps.join(' · ')}</p>` : ''}
    ${data.llm_citation_tip ? `<h2>LLM Citation Tip</h2><p>${data.llm_citation_tip}</p>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// ISSUES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type Issue = { issue: string; impact: string; category: string; fix: string }

export function exportIssuesCSV(issues: Issue[]) {
  downloadCSV('semantictoolz-issues.csv', [
    ['Issue', 'Impact', 'Category', 'Fix'],
    ...issues.map(i => [i.issue, i.impact, i.category, i.fix]),
  ])
}

export function exportIssuesPDF(issues: Issue[]) {
  const rows = issues.map(i => `<tr><td>${i.issue}</td><td><span class="badge ${i.impact}">${i.impact}</span></td><td style="color:#6b7280;font-size:10px">${i.category}</td><td style="font-size:10px">${i.fix}</td></tr>`).join('')
  downloadPDF('SemanticToolz Issues Audit', `
    <h1>Content Issues Audit</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()} · ${issues.length} issues found</p>
    <table><thead><tr><th>Issue</th><th>Impact</th><th>Category</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// ENTITIES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export function exportEntitiesCSV(gaps: string[], wins: string[]) {
  downloadCSV('semantictoolz-entities.csv', [
    ['Type', 'Value'],
    ...gaps.map(e => ['Missing Entity', e]),
    ...wins.map(w => ['Quick Win', w]),
  ])
}

export function exportEntitiesPDF(gaps: string[], wins: string[]) {
  downloadPDF('SemanticToolz Entity Gaps', `
    <h1>Entity Gap Analysis</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <h2>Missing Entities (${gaps.length})</h2>
    <p>${gaps.map(e => `<span style="display:inline-block;background:#EDE9FE;color:#5B21B6;padding:2px 10px;border-radius:99px;margin:3px;font-size:11px">${e}</span>`).join('')}</p>
    <h2>Quick Wins (${wins.length})</h2>
    <ul>${wins.map(w => `<li style="margin-bottom:6px">${w}</li>`).join('')}</ul>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// AI CITE SCORE EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type AICiteData = { scores: Record<string, number>; llm_citation_tip: string }

export function exportAICiteCSV(data: AICiteData) {
  const score = data.scores?.llm_citation_triggers ?? 0
  const verdict = score >= 75 ? 'Likely Cited' : score >= 50 ? 'Possibly Cited' : 'Unlikely Cited'
  downloadCSV('semantictoolz-aicite.csv', [
    ['Metric', 'Score', 'Verdict'],
    ['LLM Citation Triggers', String(score), verdict],
    ['E-E-A-T Signals', String(data.scores?.eeat_signals ?? 0), ''],
    ['Authority Reinforcement', String(data.scores?.authority_reinforcement ?? 0), ''],
    ['Structured Data', String(data.scores?.structured_data ?? 0), ''],
    [''],
    ['LLM Citation Tip', data.llm_citation_tip ?? ''],
  ])
}

export function exportAICitePDF(data: AICiteData) {
  const score = data.scores?.llm_citation_triggers ?? 0
  const verdict = score >= 75 ? 'Likely Cited' : score >= 50 ? 'Possibly Cited' : 'Unlikely Cited'
  const verdictClass = score >= 75 ? 'likely' : score >= 50 ? 'possible' : 'unlikely'
  downloadPDF('SemanticToolz AI Cite Score', `
    <h1>AI Citation Score Report</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>LLM Citation Score</strong></td><td style="font-size:28px;font-weight:900">${score}/100</td><td style="padding-left:24px"><span class="badge ${verdictClass}">${verdict}</span></td></tr>
    </table>
    <h2>Related Scores</h2>
    <table><thead><tr><th>Dimension</th><th>Score</th></tr></thead><tbody>
      <tr><td>E-E-A-T Signals</td><td>${data.scores?.eeat_signals ?? 0}/100</td></tr>
      <tr><td>Authority Reinforcement</td><td>${data.scores?.authority_reinforcement ?? 0}/100</td></tr>
      <tr><td>Structured Data</td><td>${data.scores?.structured_data ?? 0}/100</td></tr>
    </tbody></table>
    ${data.llm_citation_tip ? `<h2>Top LLM Citation Tip</h2><p>${data.llm_citation_tip}</p>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// E-E-A-T EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type EEATData = {
  overall: number; summary: string
  dimensions: Record<string, { score: number; finding: string }>
  recommendations: string[]
}

export function exportEEATCSV(data: EEATData) {
  downloadCSV('semantictoolz-eeat.csv', [
    ['Overall E-E-A-T Score', String(data.overall)],
    ['Summary', data.summary ?? ''],
    [''],
    ['DIMENSIONS'],
    ['Dimension', 'Score', 'Finding'],
    ...Object.entries(data.dimensions ?? {}).map(([k, v]) => [
      k.charAt(0).toUpperCase() + k.slice(1), String(v.score), v.finding
    ]),
    [''],
    ['RECOMMENDATIONS'],
    ...(data.recommendations ?? []).map(r => [r]),
  ])
}

export function exportEEATPDF(data: EEATData) {
  const dimRows = Object.entries(data.dimensions ?? {}).map(([k, v]) => `
    <tr><td style="text-transform:capitalize;font-weight:600">${k}</td><td><strong>${v.score}/100</strong></td><td style="font-size:10px">${v.finding}</td></tr>`).join('')
  downloadPDF('SemanticToolz E-E-A-T Analysis', `
    <h1>E-E-A-T Analysis Report</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    <table style="width:auto;margin-bottom:16px">
      <tr><td style="padding:4px 16px 4px 0"><strong>Overall E-E-A-T Score</strong></td><td style="font-size:28px;font-weight:900">${data.overall}/100</td></tr>
    </table>
    <p>${data.summary ?? ''}</p>
    <h2>Dimension Scores</h2>
    <table><thead><tr><th>Dimension</th><th>Score</th><th>Finding</th></tr></thead><tbody>${dimRows}</tbody></table>
    <h2>Recommendations</h2>
    <ol>${(data.recommendations ?? []).map(r => `<li style="margin-bottom:6px">${r}</li>`).join('')}</ol>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// AI REWRITE EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export function exportRewriteCSV(content: string, improvements: string[]) {
  downloadCSV('semantictoolz-rewrite.csv', [
    ['REWRITTEN CONTENT'],
    [content],
    [''],
    ['IMPROVEMENTS MADE'],
    ...improvements.map(i => [i]),
  ])
}

export function exportRewritePDF(content: string, improvements: string[]) {
  // Content is already HTML — just clean up placeholder tags
  const html = content
    .replace(/\[IMAGE PLACEHOLDER[^\]]*\]/gi, '<p style="color:#9ca3af;font-style:italic;border:1px dashed #e5e7eb;padding:8px;border-radius:4px">[Image placeholder]</p>')
    .replace(/\[INTERNAL LINK[^\]]*\]/gi, '<span style="color:#3b82f6">[Internal link]</span>')
    .replace(/\[CTA[^\]]*\]/gi, '<p style="background:#eff6ff;border:1px solid #bfdbfe;padding:8px;border-radius:4px;color:#1d4ed8">[CTA placeholder]</p>')
  downloadPDF('SemanticToolz AI Rewrite', `
    <h1>AI Rewritten Content</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${improvements.length ? `<h2>Improvements Made</h2><ul>${improvements.map(i => `<li style="margin-bottom:4px">${i}</li>`).join('')}</ul>` : ''}
    <hr style="margin:16px 0;border:none;border-top:1px solid #e5e7eb">
    <div style="line-height:1.8">${html}</div>`)
}

export function exportRewriteDOCX(content: string, improvements: string[]) {
  downloadDOCX('semantictoolz-rewrite', async () => {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, LevelFormat, BorderStyle } = await import('docx')
    const children: InstanceType<typeof Paragraph>[] = []

    if (improvements.length) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun('Improvements Made')] }))
      improvements.forEach(imp => children.push(
        new Paragraph({ numbering: { reference: 'numbers', level: 0 }, children: [new TextRun({ text: imp, size: 20 })] })
      ))
      children.push(new Paragraph({ children: [new TextRun('')] }))
      children.push(new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' } },
        children: [new TextRun('')]
      }))
      children.push(new Paragraph({ children: [new TextRun('')] }))
    }

    // Parse HTML content into docx paragraphs
    function parseInlineHTML(html: string) {
      const runs: InstanceType<typeof TextRun>[] = []
      // Split by <strong> tags
      const parts = html.replace(/<strong>(.*?)<\/strong>/gi, '||BOLD:$1||').split('||')
      parts.forEach(part => {
        if (part.startsWith('BOLD:')) {
          runs.push(new TextRun({ text: part.slice(5), bold: true, size: 20 }))
        } else if (part) {
          // Strip any remaining tags
          const clean = part.replace(/<[^>]+>/g, '')
          if (clean) runs.push(new TextRun({ text: clean, size: 20 }))
        }
      })
      return runs.length ? runs : [new TextRun({ text: '', size: 20 })]
    }

    // Simple HTML parser — handle block-level tags
    const tempDiv = content
      .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '%%H1%%$1%%END%%')
      .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '%%H2%%$1%%END%%')
      .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '%%H3%%$1%%END%%')
      .replace(/<li[^>]*>(.*?)<\/li>/gi, '%%LI%%$1%%END%%')
      .replace(/<p[^>]*>(.*?)<\/p>/gi, '%%P%%$1%%END%%')
      .replace(/<br\s*\/?>/gi, '%%BR%%')

    const blocks = tempDiv.split(/%%(?:H1|H2|H3|LI|P|BR|END)%%/)
    const tags = [...tempDiv.matchAll(/%%([A-Z0-9]+)%%/g)].map(m => m[1])

    let tagIdx = 0
    for (let i = 0; i < blocks.length; i++) {
      const tag = tags[tagIdx - 1] ?? ''
      const text = blocks[i].replace(/<[^>]+>/g, '').trim()

      if (tag === 'H1' && text) {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, size: 32, bold: true })] }))
      } else if (tag === 'H2' && text) {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, size: 28, bold: true })] }))
      } else if (tag === 'H3' && text) {
        children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text, size: 24, bold: true })] }))
      } else if (tag === 'LI' && text) {
        children.push(new Paragraph({
          numbering: { reference: 'bullets', level: 0 },
          children: parseInlineHTML(blocks[i].trim())
        }))
      } else if (tag === 'P' && text) {
        children.push(new Paragraph({ children: parseInlineHTML(blocks[i].trim()) }))
      } else if (tag === 'BR') {
        children.push(new Paragraph({ children: [new TextRun('')] }))
      } else if (text && !tag) {
        // Fallback: plain text blocks
        children.push(new Paragraph({ children: [new TextRun({ text, size: 20 })] }))
      }
      tagIdx++
    }

    const doc = new Document({
      numbering: {
        config: [
          { reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
          { reference: 'numbers', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
        ]
      },
      styles: {
        default: { document: { run: { font: 'Arial', size: 20 } } },
        paragraphStyles: [
          { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
            run: { size: 32, bold: true, font: 'Arial', color: '1E3A8A' },
            paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 } },
          { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
            run: { size: 28, bold: true, font: 'Arial', color: '1E40AF' },
            paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 1 } },
          { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true,
            run: { size: 24, bold: true, font: 'Arial', color: '1D4ED8' },
            paragraph: { spacing: { before: 160, after: 80 }, outlineLevel: 2 } },
        ]
      },
      sections: [{
        properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
        children,
      }]
    })
    return Packer.toBuffer(doc)
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// CITATION PLAN EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type CitationData = {
  summary?: string
  citation_opportunities?: Array<{ source_type: string; query: string; why: string; how_to_cite: string; priority: string }>
  citation_strategy?: string; schema_recommendations?: string[]
}

export function exportCitationCSV(data: CitationData) {
  downloadCSV('semantictoolz-citation.csv', [
    ['Source Type', 'Target Query', 'Why This Matters', 'How to Cite', 'Priority'],
    ...(data.citation_opportunities ?? []).map(c => [c.source_type, c.query, c.why, c.how_to_cite, c.priority]),
    ...(data.schema_recommendations?.length ? [[''], ['SCHEMA RECOMMENDATIONS'], ...(data.schema_recommendations ?? []).map(r => [r])] : []),
  ])
}

export function exportCitationPDF(data: CitationData) {
  const rows = (data.citation_opportunities ?? []).map(c => `
    <tr><td>${c.source_type}</td><td>${c.query}</td><td style="font-size:10px">${c.why}</td><td style="font-size:10px">${c.how_to_cite}</td><td><span class="badge ${c.priority}">${c.priority}</span></td></tr>`).join('')
  downloadPDF('SemanticToolz Citation Plan', `
    <h1>AI Citation Plan</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    ${data.citation_strategy ? `<h2>Strategy</h2><p>${data.citation_strategy}</p>` : ''}
    <h2>Citation Opportunities</h2>
    <table><thead><tr><th>Source</th><th>Query</th><th>Why</th><th>How to Cite</th><th>Priority</th></tr></thead><tbody>${rows}</tbody></table>
    ${data.schema_recommendations?.length ? `<h2>Schema Recommendations</h2><ul>${data.schema_recommendations.map(r => `<li>${r}</li>`).join('')}</ul>` : ''}`)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT GAP EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type GapData = {
  summary?: string
  gaps?: Array<{ title: string; why: string; opportunity: string; suggested_section: string }>
}

export function exportGapCSV(data: GapData) {
  downloadCSV('semantictoolz-content-gap.csv', [
    ['Gap Topic', 'Why It Matters', 'Opportunity', 'Suggested Section'],
    ...(data.gaps ?? []).map(g => [g.title, g.why, g.opportunity, g.suggested_section]),
  ])
}

export function exportGapPDF(data: GapData) {
  const rows = (data.gaps ?? []).map(g => `
    <tr><td><strong>${g.title}</strong></td><td style="font-size:10px">${g.why}</td><td style="font-size:10px">${g.opportunity}</td><td style="font-size:10px;color:#6b7280">${g.suggested_section}</td></tr>`).join('')
  downloadPDF('SemanticToolz Content Gap Analysis', `
    <h1>Content Gap Analysis</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    <table><thead><tr><th>Gap Topic</th><th>Why It Matters</th><th>Opportunity</th><th>Where to Add</th></tr></thead><tbody>${rows}</tbody></table>`)
}

// ─────────────────────────────────────────────────────────────────────────────
// AI QUERIES EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

type QueriesData = {
  summary?: string
  queries?: Array<{ query: string; intent: string; coverage: string; why: string; fix: string }>
}

export function exportQueriesCSV(data: QueriesData) {
  downloadCSV('semantictoolz-ai-queries.csv', [
    ['Query', 'Intent', 'Coverage', 'Why Important', 'Fix'],
    ...(data.queries ?? []).map(q => [q.query, q.intent, q.coverage, q.why, q.fix]),
  ])
}

export function exportQueriesPDF(data: QueriesData) {
  const rows = (data.queries ?? []).map(q => `
    <tr><td>${q.query}</td><td style="font-size:10px">${q.intent}</td><td><span class="badge ${q.coverage === 'covered' ? 'low' : q.coverage === 'partial' ? 'medium' : 'high'}">${q.coverage}</span></td><td style="font-size:10px">${q.fix}</td></tr>`).join('')
  downloadPDF('SemanticToolz AI Query Map', `
    <h1>AI Search Query Map</h1>
    <p class="meta">Generated by SemanticToolz · ${new Date().toLocaleDateString()}</p>
    ${data.summary ? `<p>${data.summary}</p>` : ''}
    <table><thead><tr><th>Query</th><th>Intent</th><th>Coverage</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>`)
}
